// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://golmwofsqcsclztyyfxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvbG13b2ZzcWNzY2x6dHl5Znh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxODU2MDAsImV4cCI6MjA0OTc2MTYwMH0.n-SDRijz2Dkf3DUHfJ11kG1x5N20-2cxr-aMrnTBbxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);